### ISSUE TITLE
При редактировании описания профиля некоторые символы выводятся как заэнкоденный HTML-код

### ISSUE THREAD

**Issue by Lumaeris** [zhabbler/zhabbler#26]
Название говорит само за себя. Должно было получиться, как на первом скриншоте, конечный результат на втором, соответственно.

![Screenshot_20240727-175827_1.jpg](https://github.com/user-attachments/assets/35f32fd3-0849-4701-a856-4ca56156962d)

![Screenshot_20240727-175857_1.jpg](https://github.com/user-attachments/assets/4feb1e99-8e12-4af8-9ea6-72420279d113)

**Comment by iamdelickkk** [comment]
https://github.com/zhabbler/zhabbler/commit/2ff17147d212f9d23cbf59e6c35d82a65d40f885
