### ISSUE TITLE
Кастомные ссылки на пост

### ISSUE THREAD

**Issue by itsailya** [zhabbler/zhabbler#44]
Сделать кастомные ссылки на пост (_например_ https://zhabbler.ru/zhab/newupdate5) для всех желающих. Не знаю, сыграет ли это большую роль, но всё таки фича полезная.

**Comment by iamdelickkk** [comment]
?)![Screenshot_20240920-153951.png](https://github.com/user-attachments/assets/7db2b423-45f1-419d-af61-a5cfb757626d)

**Comment by itsailya** [comment]
> ?)![Screenshot_20240920-153951.png](https://private-user-images.githubusercontent.com/91693467/369406919-7db2b423-45f1-419d-af61-a5cfb757626d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NDEwMDEsIm5iZiI6MTcyNzQ0MDcwMSwicGF0aCI6Ii85MTY5MzQ2Ny8zNjk0MDY5MTktN2RiMmI0MjMtNDVmMS00MTlkLWFmNjEtYTVjZmI3NTc2MjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDEyMzgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NmFmNWYwNWQ0OGU2MTQ1ZWYwY2ZiNWM2MmI5MjZlZmJhZWQ3NmIzMmQ4OWIyMmMzMDFjMjI4MDA3MDk5ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oNl3p4xUped_82JyjWP4y6NLONC7utbgcwS03vspG0w)

а ну ладно
